### ISSUE TITLE
Better output

### ISSUE THREAD

**Issue by llaumgui** [lgraubner/node-w3c-validator#3]
Hi,

why not use JUnit XML syntaxe, CSV or other output which should be used in Jenkins ?

Thx

**Comment by lgraubner** [comment]
Good Idea. So far I only used this tool for manual testing. If I have some spare time I could look into this.

**Comment by llaumgui** [comment]
The Tap syntaxe could be cool for a complet reporting : https://wiki.jenkins-ci.org/display/JENKINS/TAP+Plugin

**Comment by llaumgui** [comment]
Hi,

can you only propose a default reporter like LessHint ?
https://github.com/lesshint/lesshint

with this system, everyone can use it own reporter.
